"""init_schema

Revision ID: c0e2cf5012c1
Revises: 
Create Date: 2026-02-17 18:50:03.676426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0e2cf5012c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'COACH', 'ADMIN', name='role_enum'), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'COACH', name='plan_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('generated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('config_fingerprint', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('used_normalized', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('trend', sa.JSON(), nullable=True),
    sa.Column('latents', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.athlete_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_runs_athlete_id'), 'runs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_runs_config_fingerprint'), 'runs', ['config_fingerprint'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('exercises', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('volume_load_kg', sa.Float(), nullable=True),
    sa.Column('srpe_load', sa.Float(), nullable=True),
    sa.Column('sets_total', sa.Float(), nullable=True),
    sa.Column('reps_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.athlete_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'start_time', name='uq_session_athlete_start')
    )
    op.create_index(op.f('ix_sessions_athlete_id'), 'sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_sessions_start_time'), 'sessions', ['start_time'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_unit', sa.String(length=8), nullable=False),
    sa.Column('effort_mode', sa.String(length=8), nullable=False),
    sa.Column('modules_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_sessions_start_time'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_athlete_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_runs_config_fingerprint'), table_name='runs')
    op.drop_index(op.f('ix_runs_athlete_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('athletes')
    # ### end Alembic commands ###
