"""fix_tcac_ocr_names

Revision ID: c4f1b7e09a52
Revises: 9bcfa6c7e0cf
Create Date: 2026-09-17 00:00:00.000000

El catalogo TCAC (migracion b7d2e5f9a163) se sembro desde `data/tcac_2018.json`,
que sale de un PDF escaneado por OCR. Muchos nombres llegaron rotos y el atleta
los ve tal cual al buscar un alimento: "AQueso fresco...", "Ajonjoll o sesamo",
"Aceitedeoiva", "Plitano maritii", etc.

Esta migracion:
  1. corrige 180 nombres donde el alimento se puede identificar sin dudas
     (letras que el OCR cambio: o->d, a->s, rn->m, ll->li, n~->fi, tildes comidas,
     espacios comidos);
  2. borra 26 filas ilegibles ("Immmw.nmm", "IFI3I.Iemera.canel.emda", ...),
     donde no hay forma de saber que alimento era. Antes de borrarlas suelta la
     referencia desde `meal_entries` (esas entradas guardan su propio
     `food_name` y macros, asi que no pierden datos).

El downgrade restaura los nombres viejos; las filas borradas no se recuperan
aqui (para volver a tenerlas hay que bajar y subir b7d2e5f9a163, que re-siembra
el catalogo completo desde el JSON).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4f1b7e09a52"
down_revision: Union[str, Sequence[str], None] = "9bcfa6c7e0cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# source_ref (codigo TCAC) -> nombre corregido
RENAMES: dict[str, str] = {
    'A033': 'Harina de centeno, para panificación, cruda',
    'A034': 'Harina de centeno, para repostería, cruda',
    'A039': 'Harina de quinua, cruda',
    'A040': 'Harina de trigo, fortificada, para panificación, cruda',
    'A041': 'Harina de trigo, fortificada, para repostería, cruda',
    'A042': 'Harina de trigo, fortificada, todo propósito, cruda',
    'A045': 'Maíz amarillo, crudo',
    'A053': 'Maíz pira o reventón, crudo',
    'A057': 'Mezcla lista para preparar pancakes, en polvo',
    'A059': 'Mogolla, integral, horneada',
    'A060': 'Mojicón, horneado',
    'A062': 'Pan blanco, regular, horneado',
    'A065': 'Pan de dulce, regular, horneado',
    'A069': 'Pan de yuca, horneado',
    'A075': 'Pasta alimenticia, sin enriquecer, cocida, sin sal',
    'A077': 'Ponqué blanco, cubierto de chocolate, horneado',
    'A081': 'Ponqué negro, cubierto de chocolate, horneado',
    'A086': 'Roscón, relleno de arequipe, horneado',
    'A087': 'Roscón, relleno de bocadillo, horneado',
    'A088': 'Semolina, enriquecida, cruda',
    'B007': 'Ají dulce, crudo',
    'B008': 'rojo, crudo',
    'B012': 'Almidón de achira, crudo',
    'B020': 'Balú o chachafruto verde, crudo',
    'B025': 'Brócoli, crudo',
    'B032': 'Cebolla, pasta escaldada',
    'B033': 'Champiñón, crudo',
    'B034': 'Champiñón, en conserva',
    'B036': 'Col o repollitas de bruselas, cruda',
    'B050': 'Haba verde, cruda',
    'B055': 'Harina de papa común, cruda',
    'B060': 'Lechuga romana, cruda',
    'B068': 'Papa variedad cerosa, sabanera, sin cáscara, cocida, sin sal',
    'B073': 'Papa, variedad harinosa, criolla, con cáscara, cruda',
    'B075': 'Papa, variedad harinosa, pastusa, con cáscara, cocida, sin sal',
    'B082': 'Pimentón rojo, crudo',
    'B090': 'Plátano hartón, maduro, cocido, sin sal',
    'B092': 'Plátano hartón, maduro, frito, en tajadas, sin sal',
    'B094': 'Plátano hartón, verde, crudo',
    'B095': 'Plátano hartón, verde, frito, en patacón, sin sal',
    'B098': 'Remolacha, sin cáscara, cocida, sin sal',
    'B103': 'Salsifí, sin cáscara, crudo',
    'B107': 'Yuca blanca, sin cáscara, cocida, sin sal',
    'B110': 'Zanahoria, sin cáscara, cruda',
    'C004': 'Anón, crudo',
    'C006': 'Babaco, pintón, crudo',
    'C018': 'Citrón, crudo',
    'C022': 'Dátil, seco',
    'C039': 'Higo, pintón, crudo',
    'C047': 'Madroño, crudo',
    'C051': 'Mango común, crudo',
    'C057': 'Marañón, frito, sin sal',
    'C058': 'Marañón, seco',
    'C059': 'Marañón, tostado, sin sal',
    'C060': 'Melón, crudo',
    'C068': 'Pepino dulce, maduro, crudo',
    'C070': 'Pepino dulce, verde, crudo',
    'C076': 'Pitahaya roja, cruda',
    'C082': 'Tomate de árbol rojo, crudo',
    'C084': 'Uchuva, cruda',
    'C088': 'Zapote blanco, crudo',
    'D001': 'Aceite de ajonjolí o sésamo',
    'D008': 'Aceite de oliva',
    'D016': 'Mantequilla de maní',
    'E004': 'Atún, enlatado en agua',
    'E016': 'Camarón, cocido, sin sal',
    'E027': 'Lisa, sin cabeza, salada, cruda',
    'E028': 'Macabi o machete, entero, crudo',
    'E038': 'Salmón, filete, crudo',
    'E042': 'Tiburón, filete, crudo',
    'F006': 'Caracol terrestre, carne, cruda',
    'F009': 'Cerdo, brazo, horneado, sin sal',
    'F014': 'Cerdo, costilla, cocida, sin sal',
    'F017': 'Cerdo, hígado, crudo',
    'F023': 'Cerdo, panceta o tocineta, salteada, sin sal',
    'F024': 'Cerdo, pierna o pernil, cocida, sin sal',
    'F026': 'Cerdo, pierna o pernil, horneada, sin sal',
    'F030': 'Cerdo, tocino, frito en su propia grasa (chicharrón), con sal',
    'F032': 'Chigüiro, carne, salada, cruda',
    'F033': 'Chigüiro, pierna o pernil, cruda',
    'F035': 'Chorizo de pollo, crudo',
    'F036': 'Codorniz o perdiz, entera sin piel, cruda',
    'F037': 'Conejo, carne, cocida, sin sal',
    'F039': 'Conejo, hígado, crudo',
    'F040': 'Conejo, riñón, crudo',
    'F045': 'Cordero, corazón, crudo',
    'F047': 'Cordero, riñón, crudo',
    'F048': 'Gallina, entera con piel, cruda',
    'F049': 'Hamburguesa de carne de res, cruda',
    'F051': 'Jamón de cerdo y res, tipo sánduche, precocido',
    'F052': 'Jamón de cerdo, crudo',
    'F065': 'Pavo, pierna o pernil sin piel, horneada, sin sal',
    'F077': 'Pollo, corazón, crudo',
    'F083': 'Pollo, menudencias, crudas',
    'F096': 'Res, bofe o pulmón, crudo',
    'F103': 'Res, carne semigorda, molida, cruda',
    'F107': 'Res, corazón, crudo',
    'F108': 'Res, corazón, dorado, sin sal',
    'F117': 'Res, pajarilla o bazo, cruda',
    'F120': 'Res, pierna, cruda',
    'F121': 'Res, riñón, crudo',
    'F129': 'Salchicha de ternera, precocida',
    'F133': 'Tortuga, carne, cruda',
    'G004': 'Leche de cabra, entera, líquida, cruda',
    'G007': 'Leche de vaca, descremada, líquida, pasteurizada',
    'G010': 'Leche de vaca, entera, líquida, cruda',
    'G011': 'Leche de vaca, entera, líquida, hervida',
    'G012': 'Leche de vaca, entera, líquida, pasteurizada',
    'G013': 'Leche humana, madura, líquida',
    'G015': 'Queso fresco, blando, magro, tipo suero costeño',
    'G018': 'Queso fresco, semiduro, semigraso, tipo costeño',
    'G020': 'Queso fresco, semiduro, semimagro, de pasta hilada',
    'G025': 'Queso madurado, duro, semigraso, tipo roquefort',
    'G028': 'Yogur, bebible, entero, con azúcar',
    'H003': 'Bebida de avena en hojuelas, en agua, sin azúcar',
    'H004': 'Bebida de harina de avena, en agua, sin azúcar',
    'H005': 'Café, tostado y molido, infusión al 6%, sin azúcar',
    'H009': 'Guarapo de caña de azúcar, 3% de alcohol',
    'H014': 'Néctar de manzana, con azúcar',
    'H016': 'Sabajón de tomate de árbol amarillo, 14% de alcohol',
    'H017': 'Sabajón de tomate de árbol rojo, 14% de alcohol',
    'K003': 'Azúcar blanco, granulado',
    'K005': 'Bocadillo o dulce de guayaba, tradicional',
    'K006': 'Bocadillo o dulce de guayaba, veleño',
    'K016': 'Dulce de coco, con almendras',
    'K018': 'Dulce de lulo',
    'K020': 'Gelatina con azúcar, líquida',
    'K022': 'Goma de mascar, con azúcar',
    'K023': 'Helado de agua, con azúcar',
    'K030': 'Melocotón, en almíbar',
    'K031': 'Mermelada, regular, con azúcar',
    'L004': 'Café soluble, descafeinado, en polvo',
    'L005': 'Café soluble, en polvo',
    'L012': 'Moringa, en polvo',
    'L014': 'Polen seco',
    'L016': 'Salsa de mostaza',
    'N002': 'Mayonesa, baja en grasa',
    'N004': 'Salchicha de cerdo, baja en grasa',
    'P003': 'Ackee, crudo',
    'P005': 'Almidón de malanga, crudo',
    'P006': 'Almidón de ñame, crudo',
    'P007': 'Arazá, crudo',
    'P011': 'Asaí, cocido, sin sal',
    'P013': 'Asaí, deshidratado',
    'P014': 'Asaí, liofilizado',
    'P016': 'Banano pacífico, crudo',
    'P017': 'Borojó, crudo',
    'P025': 'Carambolo, pintón, crudo',
    'P026': 'Carambolo, pintón, deshidratado',
    'P030': 'Cardón guajiro, asado, sin sal',
    'P031': 'Carurú, cocido, sin sal',
    'P032': 'Carurú, crudo',
    'P038': 'Chontaduro amazónico, crudo',
    'P044': 'Concha de caimán, cruda',
    'P045': 'Copoazú, crudo',
    'P053': 'Dulce de borojó',
    'P064': 'Malanga, sin cáscara, cruda',
    'P070': 'Níspero del Japón, crudo',
    'P072': 'Ñame, con cáscara, crudo',
    'P073': 'Ñame, sin cáscara, cocido',
    'P074': 'Ñame, sin cáscara, crudo',
    'P077': 'Olloco o chugua, con cáscara, cruda',
    'P078': 'Olloco o chugua, sin cáscara, cruda',
    'P080': 'Paja toquilla, cruda',
    'P088': 'Trigo amazónico, crudo',
    'R008': 'Bienestarina, líquida, sabor a vainilla natural',
    'S001': 'Ajiaco santafereño',
    'S007': 'Chicharrón de pirarucú, frito',
    'S020': 'Masa zamorra chiquita',
    'S023': 'Pisillo de chigüiro',
    'S027': 'Sopa de arroz',
    'S031': 'Tamal de maíz, cocido',
    'T001': 'Ajonjolí o sésamo, crudo',
    'T003': 'Arveja seca, cruda',
    'T004': 'Bebida vegetal, de soya, líquida, sin azúcar',
    'T010': 'Frijol cargamanto rojo, cocido, sin sal',
    'T020': 'Haba seca, cruda',
    'T021': 'Harina de algarrobo, cruda',
    'T025': 'Lenteja común, cocida, sin sal',
    'T029': 'Maní, con piel, tostado, sin sal',
}

# source_ref -> nombre tal como lo dejo el OCR (para el downgrade)
OCR_NAMES: dict[str, str] = {
    'A033': 'Harina de centeno, para panificacion, cruda',
    'A034': 'Harina de centeno, para reposteria, cruda',
    'A039': 'Harina de guinua, cruda',
    'A040': 'Harina de trigo, fortificada, para panificacion, cruda',
    'A041': 'Harina de trigo, fortificada, para reposteria, cruda',
    'A042': 'Harina de trigo, fortificada, todo propdsito, cruda',
    'A045': 'Maíz amarilio, crudo',
    'A053': 'Maíz pira o reventon, crudo',
    'A057': 'Mezcla lista para preparar pancakss, en polvo',
    'A059': 'Mogolla, integral, hornesada',
    'A060': 'Mojicon, hormeado',
    'A062': 'FPan blanco, regular, horneado',
    'A065': 'FPan de dulce, regular, hornsado',
    'A069': 'FPan de yuca, horneado',
    'A075': 'Pasta alimenticia, sin enriguecer, cocida, sin sal',
    'A077': 'Pongué blanco, cubierto de chocolate, horneado',
    'A081': 'Pongueé negro, cubierto de chocolate, horneado',
    'A086': 'Roscon, relleno de arsquipe, horneado',
    'A087': 'Roscon, relleno de bocadillo, horneado',
    'A088': 'Semoling, enriquecida, cruda',
    'B007': 'Aji dulce, crudo',
    'B008': 'rojo. crudo',
    'B012': 'Almiddn de achira, crudo',
    'B020': 'Ball o chachafruto verde, crudeo',
    'B025': 'Brocoli, crudo',
    'B032': 'Cebolls, pasta escaldada',
    'B033': 'Champinon, crudo',
    'B034': 'Champifion, en conserva',
    'B036': 'Col o repollitas de brusslas, cruda',
    'B050': 'Habs verde, cruda',
    'B055': 'Harinz de papa común, cruda',
    'B060': 'Lechuga romans, cruda',
    'B068': 'Ppa variedad cerosa, sabanera, sin cáscara, cocida, sin',
    'B073': 'Papa, variedad harinosa, criollz, con cáscara, cruda',
    'B075': 'Fapa. variedad harinosa, pastusa, con cáscara, cocida, sin',
    'B082': 'Pimenton rojo, crudo',
    'B090': 'Plátano hartén, maduro, cocido, sin sal',
    'B092': 'Plátano hartén, maduro, frito, en tajadas, sin sal',
    'B094': 'Pistano hartén, verde, crudo',
    'B095': 'Plétano hartdn, verde, frito, en patacén, sin sal',
    'B098': 'Remolacha, sin céscara, cocida, sin sal',
    'B103': 'Salsifi, sin céscara, crudo',
    'B107': 'Yuca blanca, sin ciscara, cocida, sin sal',
    'B110': 'Zanahoria, sin ciscara, cruda',
    'C004': 'Andn, crudo',
    'C006': 'Babaco, pintdn, crudo',
    'C018': 'Citron, crudo',
    'C022': 'Datil, seco',
    'C039': 'Higo, pintén, crudo',
    'C047': 'Madrono, crudo',
    'C051': 'Mango comun, crudo',
    'C057': 'Maranon, frito, sin sal',
    'C058': 'Maranon, seco',
    'C059': 'Maranon, tostado, sin sal',
    'C060': 'Meldn, crudo',
    'C068': 'Pepino dulce, maduro,crudo',
    'C070': 'Pepino dulce, verde,crudo',
    'C076': 'Pitahaya roja. cruda',
    'C082': 'Tomatedeérbolrojo,crudo',
    'C084': 'Uchuva,cuda',
    'C088': 'Zapoteblanco.crudo',
    'D001': 'Aceite de ajonjolí 0 sésamo',
    'D008': 'Aceitedeoiva',
    'D016': 'Mantequilademani',
    'E004': 'Atin, enlatado en agua',
    'E016': 'Camardn, cocido, sin sal',
    'E027': 'Liss, sin cabeza, salads, cruda',
    'E028': 'Macabi o machete, entzro, crudo',
    'E038': 'Salmén,filetecudo',
    'E042': 'Tiburdn,filete,crudo',
    'F006': 'Caracol terrestre, camne, cruda',
    'F009': 'Cerdo, brazo, hormeado, sin sal',
    'F014': 'Cerdo, costills, cocida, sin sal',
    'F017': 'Cerdo, hígado. crudo',
    'F023': 'Cerdo, panceta o tocineta, salteads, sin sal',
    'F024': 'Cerdo, piema o pemil, cocida, sin sal',
    'F026': 'Cerdo, pierna o pemnil, horneada. sin sal',
    'F030': 'Cerdo, tocino, frito en su propia grasa (chicharron), con sal',
    'F032': 'Chiguiro, carne, salada, cruda',
    'F033': 'Chiguiro, pierna o pemil, cruda',
    'F035': 'Chorizo de pollo, crude',
    'F036': 'Codomiz o perdiz, entera sin piel, cruda',
    'F037': 'Conejo, camne, cocida, sin sal',
    'F039': 'Consjo. hígado, crudo',
    'F040': 'Conejo, rindn, crudo',
    'F045': 'Cordero, corazon, crudo',
    'F047': 'Cordero, rifon, crudo',
    'F048': 'Gallina, entera con piel. cruda',
    'F049': 'Hamburguess de carne de res, cruda',
    'F051': 'Jamón de cerdo y res, tipo sanduche, precocido',
    'F052': 'Jamén de cerdo, crudo',
    'F065': 'Pavo, pierna o pernil sin piel, hormeada, sin sal',
    'F077': 'Pollo, corazdn, crudo',
    'F083': 'Pollo, menudencia %, srudas',
    'F096': 'Res, bofe o pulman, crudo',
    'F103': 'Res, carne semigorda, molids, cruda',
    'F107': 'Res, corazon, crudo',
    'F108': 'Res, corazon, dorado, sin sal',
    'F117': 'Res, psjarilla o bazo, cruda',
    'F120': 'Res, piemna, cruda',
    'F121': 'Res, rifidn, crudo',
    'F129': 'Salchicha de tenera, precocida',
    'F133': 'Tortuga,came,cuda',
    'G004': 'Leche de cabra, entera, liquida, cruda',
    'G007': 'Leche de vaca, descremada. liquida, pasteurizada',
    'G010': 'Leche de vaca, entera, liquida, cruda',
    'G011': 'Leche de vaca, entera, liquida, hervida',
    'G012': 'Leche de vaca, entera, liquida, pasteurizada',
    'G013': 'Leche humana, madura, liquida',
    'G015': 'Queso fresco, blando, magro, tipo suero costeno',
    'G018': 'AQueso fresco, semiduro, semigraso, tipo costeio',
    'G020': 'AQueso fresco, semiduro, semimagro, de pasta hilada',
    'G025': 'Queso madurado, duro, semigraso, tipo roguefort',
    'G028': 'Yogurt, bebible, entero, con azúcar',
    'H003': 'Bebida de avena en hojuelas, en agua, sin azlicar',
    'H004': 'Bebida de harina de avena, en agua, sin azlicar',
    'H005': 'Café, tostado y molido, infusidn al 6%, sin azúcar',
    'H009': 'Guarapo de caha de azúcar, 3% de alcohol',
    'H014': 'Néctar de manzana,conaricar',
    'H016': 'Sabajén de tomate de árbol amarillo, 14% de alcohol',
    'H017': 'Sabajén de tomate de árbol rojo, 14% de alcohol',
    'K003': 'Azicar blanco, granulado',
    'K005': 'Bocadilio o dulce de guayaba, tradicional',
    'K006': 'Bocadillo o dulce de guayaba, velefo',
    'K016': 'Duice de coco, con almendras',
    'K018': 'Duice de lulo',
    'K020': 'Gelatina con azúcar, liquida',
    'K022': 'Goma de mascar, con azicar',
    'K023': 'Helado de agua. con azúcar',
    'K030': 'Melocoton, en almibar',
    'K031': 'Mermelada, regular, con azlicar',
    'L004': 'Café soluble. descafeinado, en polvo',
    'L005': 'Café soluble, en poivo',
    'L012': 'Moringa,enpov0',
    'L014': 'Polenseco',
    'L016': 'Salsademostaza',
    'N002': 'Mayonesa, bajaengrasa',
    'N004': 'Salchicha de cerdo, bajaengrasa',
    'P003': 'Ackee, crude',
    'P005': 'Almiddn de malanga, crudo',
    'P006': 'Almidón de hame, crudo',
    'P007': 'Araza, crudo',
    'P011': 'Asai, cocido, sin sal',
    'P013': 'Asai, deshidratado',
    'P014': 'Asai, liofilizado',
    'P016': 'Banano pacifico, crudo',
    'P017': 'Borojo, crudo',
    'P025': 'Carambolo, pinton, crudo',
    'P026': 'Carambolo, pintén, deshidratado',
    'P030': 'Cardén Guajiro, asado, sin sal',
    'P031': 'Carurd, cocido, sin sal',
    'P032': 'Carurd, crudo',
    'P038': 'Chontaduro amazonico, crudo',
    'P044': 'Concha de caiman, cruda',
    'P045': 'Copoazl, crudo',
    'P053': 'Duice de borojo',
    'P064': 'Malanga, sin cascars, cruda',
    'P070': 'Nispero del Japon, crudo',
    'P072': 'Name, con cáscara, crudo',
    'P073': 'RName, sin cascars, cocido',
    'P074': 'RName, sin cáscara, crudo',
    'P077': 'Olioco o chugua, con cáscara, cruda',
    'P078': 'COlloco o chugua, sin cáscara, cruda',
    'P080': 'Psja toquilla, cruda',
    'P088': 'Trigo amazonico, crudo',
    'R008': 'Bienestarina, liquida, sabor a vainilla natural',
    'S001': 'Ajiaco santafersio',
    'S007': 'Chicharrdn de pirarucd, frito',
    'S020': 'Masazamorra chiquita',
    'S023': 'Pisillo de chigtiro',
    'S027': 'Sopade arroz',
    'S031': 'Tamalde maíz,cocidlo',
    'T001': 'Ajonjoll o sésamo, crudo',
    'T003': 'Arvejs seca, cruda',
    'T004': 'Bebids vegetal, de soya, liquida, sin azGcar',
    'T010': 'Frijol cargamanto rojo. cocido, sin sal',
    'T020': 'Haba secs, cruda',
    'T021': 'Harina de zlgarrobo, cruda',
    'T025': 'Lentsja comdn, cocida, sin sal',
    'T029': 'Manl, con piel, tostado, sin sal',
}

# Filas ilegibles: se borran porque el nombre no permite identificar el alimento.
DELETE_REFS: tuple[str, ...] = (
    'B071',
    'B093',
    'B096',
    'B097',
    'B106',
    'B108',
    'C087',
    'D013',
    'E031',
    'E035',
    'F126',
    'F130',
    'F132',
    'H011',
    'J009',
    'J013',
    'K032',
    'K035',
    'L009',
    'N001',
    'P039',
    'P051',
    'P052',
    'P054',
    'P055',
    'P084',
)

# Nombres originales de lo que se borra, solo como rastro en el historial.
DELETED_OCR_NAMES: dict[str, str] = {
    'B071': 'frrc Cachia conansr s A ks',
    'B093': 'Iaogfmmnmén.m.ooem.si-sa',
    'B096': 'Plitano maritii, maduro, crudo',
    'B097': 'IMMMMo.m.auuo',
    'B106': 'Tomate.emacto.fresco',
    'B108': 'Immmw.nmm',
    'C087': 'Iamwadsmm',
    'D013': 'IDOSMdm.lnemlavegenl',
    'E031': 'IEMI.Mem.enm.cmdo',
    'E035': 'IEossnaya.m.asado',
    'F126': 'IFEVdeimanrdoyres.pteoocih',
    'F130': 'IF129Vdeidb6ndeeerdoypob.mo.preoudo',
    'F132': 'IFI3I.Iemera.canel.emda',
    'H011': 'Imnuécxzdewram.eonmw',
    'J009': 'Imuumdegan.m.auao',
    'J013': 'ImlaHuevodelnnuga.emao.m',
    'K032': 'Immudeabqas.iquua',
    'K035': 'Ixoas.unm.enm',
    'L009': 'ILonumnbauégiupmpm.frescamngda',
    'N001': 'Magain,bqaMCdmfs.m',
    'P039': 'Chups, cruda',
    'P051': 'Ductli simple, sin cáscara, cocido, sin sal',
    'P052': 'Ductl simple, sin cáscara, crudo',
    'P054': 'Duri, crudo',
    'P055': 'Emi, crudo',
    'P084': 'Pinz uva hartón, cruda',
}


def _apply(names: dict[str, str]) -> None:
    bind = op.get_bind()
    for source_ref, name in names.items():
        bind.execute(
            sa.text(
                "UPDATE food_products SET name = :name "
                "WHERE source = 'tcac' AND source_ref = :source_ref"
            ),
            {"name": name, "source_ref": source_ref},
        )


def upgrade() -> None:
    _apply(RENAMES)

    bind = op.get_bind()
    # Las comidas ya registradas conservan su propio nombre y macros; solo se
    # les quita el puntero al producto que se va a borrar.
    bind.execute(
        sa.text(
            "UPDATE meal_entries SET food_product_id = NULL "
            "WHERE food_product_id IN ("
            "  SELECT id FROM food_products "
            "  WHERE source = 'tcac' AND source_ref = ANY(:refs)"
            ")"
        ),
        {"refs": list(DELETE_REFS)},
    )
    bind.execute(
        sa.text(
            "DELETE FROM food_products WHERE source = 'tcac' AND source_ref = ANY(:refs)"
        ),
        {"refs": list(DELETE_REFS)},
    )


def downgrade() -> None:
    _apply(OCR_NAMES)
